"""Pydantic request/response models for API validation."""

from typing import List, Literal, Optional

from pydantic import BaseModel, Field, field_validator


class TileInput(BaseModel):
    """Represents a mahjong tile in API requests."""
    suit: Literal["TONG", "TIAO", "WAN"] = Field(..., description="Tile suit")
    rank: int = Field(..., ge=1, le=9, description="Tile rank (1-9)")

    class Config:
        json_schema_extra = {
            "example": {
                "suit": "TONG",
                "rank": 5
            }
        }


class CreateGameRequest(BaseModel):
    """Request body for POST /games.

    Optional Configuration:
        player_ids: Custom player IDs (must be exactly 4).
                    If omitted, generates ["human", "ai_1", "ai_2", "ai_3"].
    """
    player_ids: Optional[List[str]] = Field(
        None,
        min_length=4,
        max_length=4,
        description="List of 4 player IDs. Default: 1 human + 3 AI."
    )

    class Config:
        json_schema_extra = {
            "example": {
                "player_ids": ["alice", "ai_1", "ai_2", "ai_3"]
            }
        }


class PlayerActionRequest(BaseModel):
    """Request body for POST /games/{game_id}/action.

    Action Types:
        - bury: Requires 3 tiles (埋牌阶段)
        - draw: Manual draw tile (debug interface, normally automatic)
        - discard: Requires 1 tile (出牌)
        - peng/gang/hu: Requires tile from opponent's discard
        - skip: No tiles required
    """
    player_id: str = Field(..., description="ID of the player taking action")
    action: Literal["bury", "draw", "discard", "peng", "gang", "hu", "skip"] = Field(
        ..., description="Action type"
    )
    tiles: Optional[List[TileInput]] = Field(
        None, description="Tiles involved (required for bury/discard/peng/gang)"
    )

    @field_validator("tiles")
    @classmethod
    def validate_tiles_for_action(cls, v, info):
        action = info.data.get("action")
        if action == "bury" and (not v or len(v) != 3):
            raise ValueError("Bury action requires exactly 3 tiles")
        if action in ["discard"] and (not v or len(v) != 1):
            raise ValueError(f"{action} action requires exactly 1 tile")
        if action in ["skip"] and v:
            raise ValueError("Skip action should not include tiles")
        return v

    class Config:
        json_schema_extra = {
            "examples": [
                {
                    "player_id": "human",
                    "action": "bury",
                    "tiles": [
                        {"suit": "TONG", "rank": 1},
                        {"suit": "TONG", "rank": 2},
                        {"suit": "TONG", "rank": 3}
                    ]
                },
                {
                    "player_id": "human",
                    "action": "discard",
                    "tiles": [{"suit": "WAN", "rank": 5}]
                },
                {
                    "player_id": "human",
                    "action": "skip",
                    "tiles": None
                }
            ]
        }


class CreateGameResponse(BaseModel):
    """Response for POST /games.

    Returns:
        game_id: UUID for subsequent API calls
        state: Initial game state (filtered for human player)
    """
    game_id: str = Field(..., description="UUID v4 identifier")
    state: dict = Field(..., description="Initial game state (burying phase)")


class GameStateResponse(BaseModel):
    """Response for GET /games/{game_id} and POST /games/{game_id}/action.

    Returns filtered view based on `player_id` query parameter.
    Reuses `GameState.to_dict_for_player()` output.
    """
    game_id: str = Field(..., description="Game UUID")
    game_phase: Literal["BURYING", "PLAYING", "ENDED"] = Field(
        ..., description="Current game phase"
    )
    current_player_index: int = Field(..., description="Index of current turn player (0-3)")
    players: List[dict] = Field(..., description="Player states (filtered by viewer)")
    public_discards: List[dict] = Field(..., description="All discarded tiles (public)")
    wall_remaining_count: int = Field(..., description="Tiles left in wall")
    winners: Optional[List[dict]] = Field(None, description="Win details if game ended")


class ErrorResponse(BaseModel):
    """Standard error response (FastAPI default format).

    Automatically generated by HTTPException.
    """
    detail: str = Field(..., description="Human-readable error message")
